import '../styles/globals.scss'
import { Open_Sans } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  content: "width=device-width, initial-scale=1",
  name:"viewport",
}

const openSans = Open_Sans({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>{children}</body>
    </html>
  )
}
